name: trivia_fun
description: New age app for trivia and fun

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.8.1
  http: ^0.12.2
  progress_dialog: ^1.2.4
  device_info:  ^0.4.2+7
  shared_preferences: ^0.5.12+4
  fluttertoast: ^7.1.6
  sqflite: ^1.3.2+2
  path_provider: ^1.6.27
  image_picker: ^0.6.7+22
  image_cropper: ^1.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: "images/appicon/trivia_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "images/appicon/trivia_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/background1.png
    - images/reg_background.png
    - wave.gif
    - double_ring_loading_io.gif
    - dashboard_back.png
    - user_avatar.png
    - user_avatar2.png
    - coin.png
    - coin2.png
    - number_of_games.png
    - percentage.png
    - trophy.png
    - coin3.png
    - badge.png
    - menu.png

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/FontsFree-Net-SFProDisplay-Regular.ttf
    - family: PoppinsRegular
      fonts:
        - asset: fonts/Poppins-Regular-400.ttf
    - family: PoppinsThin
      fonts:
        - asset: fonts/Poppins-Thin-250.ttf
    - family: Poweto
      fonts:
        - asset: fonts/Poweto-4BEZx.otf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
